name: CS.Trade Watcher
on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allow manual triggering as well

jobs:
  check-cs-trade-items:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing commits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check for new CS.Trade items
        run: npm run cs-trade
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          NODE_OPTIONS: "--max-old-space-size=2048" # Lower memory limit since we're only processing CS.Trade

      - name: Commit and push changes if any
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          git diff --staged --quiet || (git commit -m "Update CS.Trade item data" && git push)
